name: Test Flutter Frontend on Main

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Enable Flutter Web
        run: flutter config --enable-web

      - name: Check Flutter version
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project code without blocking PR
        run: flutter analyze lib test || true

      - name: Run tests
        run: flutter test

      - name: Build Flutter Web
        run: flutter build web --release